export const COMPETITION_GROUPS: { label: string; items: string[] }[] = [
  {
    label: "Europe — Élite",
    items: [
      "Angleterre — Premier League",
      "Angleterre — Championship",
      "Angleterre — League One",
      "Angleterre — FA Cup",
      "Angleterre — EFL Cup",
      "Espagne — LaLiga",
      "Espagne — LaLiga 2",
      "Espagne — Copa del Rey",
      "Italie — Serie A",
      "Italie — Serie B",
      "Italie — Coppa Italia",
      "Allemagne — Bundesliga",
      "Allemagne — 2. Bundesliga",
      "Allemagne — DFB Pokal",
      "France — Ligue 1",
      "France — Ligue 2",
      "France — Coupe de France",
    ],
  },
  {
    label: "Europe — Autres championnats",
    items: [
      "Portugal — Primeira Liga",
      "Pays-Bas — Eredivisie",
      "Belgique — Pro League",
      "Turquie — Süper Lig",
      "Écosse — Premiership",
      "Suisse — Super League",
      "Autriche — Bundesliga",
      "Grèce — Super League",
      "Danemark — Superliga",
      "Norvège — Eliteserien",
      "Suède — Allsvenskan",
      "Pologne — Ekstraklasa",
      "Tchéquie — Fortuna Liga",
      "Croatie — HNL",
      "Serbie — SuperLiga",
      "Ukraine — Premier League",
      "Russie — Premier League",
      "Roumanie — Superliga",
      "Israël — Ligat ha'Al",
      "Irlande — Premier Division",
      "Finlande — Veikkausliiga",
    ],
  },
  {
    label: "Coupes internationales de clubs",
    items: [
      "UEFA Champions League",
      "UEFA Europa League",
      "UEFA Conference League",
      "UEFA Supercoupe",
      "Copa Libertadores",
      "Copa Sudamericana",
      "CAF Ligue des Champions",
      "CAF Coupe de la Confédération",
      "AFC Champions League",
      "CONCACAF Champions Cup",
      "Coupe du Monde des Clubs FIFA",
    ],
  },
  {
    label: "Sélections nationales",
    items: [
      "Coupe du Monde FIFA",
      "Qualifications Coupe du Monde",
      "UEFA Euro",
      "Qualifications Euro",
      "UEFA Nations League",
      "Copa América",
      "CAN (Coupe d'Afrique des Nations)",
      "Qualifications CAN",
      "Coupe d'Asie AFC",
      "Gold Cup CONCACAF",
      "Match amical international",
    ],
  },
  {
    label: "Amériques",
    items: [
      "Brésil — Serie A",
      "Brésil — Serie B",
      "Brésil — Copa do Brasil",
      "Argentine — Liga Profesional",
      "Argentine — Copa Argentina",
      "Mexique — Liga MX",
      "États-Unis — MLS",
      "Colombie — Primera A",
      "Chili — Primera División",
      "Uruguay — Primera División",
      "Pérou — Liga 1",
      "Équateur — Liga Pro",
      "Paraguay — Primera División",
    ],
  },
  {
    label: "Afrique",
    items: [
      "Égypte — Premier League",
      "Maroc — Botola Pro",
      "Tunisie — Ligue Professionnelle 1",
      "Algérie — Ligue 1",
      "Afrique du Sud — Premiership",
      "Nigéria — NPFL",
      "Bénin — Ligue Pro",
      "Côte d'Ivoire — Ligue 1",
      "Sénégal — Ligue 1",
      "Ghana — Premier League",
      "Cameroun — Elite One",
      "RD Congo — Linafoot",
    ],
  },
  {
    label: "Asie & Océanie",
    items: [
      "Japon — J1 League",
      "Corée du Sud — K League 1",
      "Chine — Super League",
      "Arabie Saoudite — Saudi Pro League",
      "Qatar — Stars League",
      "Émirats — Pro League",
      "Iran — Persian Gulf Pro League",
      "Inde — ISL",
      "Australie — A-League",
      "Thaïlande — Thai League 1",
      "Indonésie — Liga 1",
      "Vietnam — V.League 1",
    ],
  },
  {
    label: "Autres",
    items: [
      "Football féminin",
      "Championnat U21 / U19 / réserves",
      "Match amical de clubs",
    ],
  },
];

export const OTHER_COMPETITION = "__other__";
