/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoriqueIndexRouteImport } from './routes/historique/index'
import { Route as HistoriqueIdRouteImport } from './routes/historique/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueIndexRoute = HistoriqueIndexRouteImport.update({
  id: '/historique/',
  path: '/historique/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueIdRoute = HistoriqueIdRouteImport.update({
  id: '/historique/$id',
  path: '/historique/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/historique/$id': typeof HistoriqueIdRoute
  '/historique/': typeof HistoriqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/historique/$id': typeof HistoriqueIdRoute
  '/historique': typeof HistoriqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/historique/$id': typeof HistoriqueIdRoute
  '/historique/': typeof HistoriqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/historique/$id' | '/historique/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/historique/$id' | '/historique'
  id: '__root__' | '/' | '/live' | '/historique/$id' | '/historique/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  HistoriqueIdRoute: typeof HistoriqueIdRoute
  HistoriqueIndexRoute: typeof HistoriqueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique/': {
      id: '/historique/'
      path: '/historique'
      fullPath: '/historique/'
      preLoaderRoute: typeof HistoriqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique/$id': {
      id: '/historique/$id'
      path: '/historique/$id'
      fullPath: '/historique/$id'
      preLoaderRoute: typeof HistoriqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  HistoriqueIdRoute: HistoriqueIdRoute,
  HistoriqueIndexRoute: HistoriqueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
